import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  FR: {
    home: "Home",
    card: "Carte",
    destination: "Destination",
    languages: "Apprendre",
    pack: "Planificateur",
    saved: "Sauvegardes",
    login: "Connexion",
    darkMode: "Mode Sombre",
    lightMode: "Mode Clair",
    translation: "Traduction",
    settings: "Parametres",
    heroTitle: "Decouvrez de Belles Destinations",
    heroSubtitle: "Voyagez, Explorez et Vivez des moments inoubliables",
    exploreBtn: "Explorer",
    topPlaces: "TOP PLACES",
    popularDestinations: "Destinations Populaires",
    viewAll: "Voir tout",
    chatbotGreeting: "Bonjour ! Je suis votre assistant AMUDUX. Comment puis-je vous aider a decouvrir le Maroc ?",
    chatbotPlaceholder: "Ecrire un message...",
    chatbotClear: "Effacer",
    chatbotOnline: "En ligne",
    chatbotAssistant: "Assistant AMUDUX",
    chip1: "Marrakech",
    chip2: "Hotels",
    chip3: "Activites",
    chip4: "Prix",
    cardTitle: "Carte des Destinations",
    cardSubtitle: "Destinations proches de vous",
    locating: "Localisation en cours...",
    locateMe: "Ma position",
    locError: "Geolocalisation refusee. Vue sur le Maroc.",
    searchPlaceholder: "Rechercher une ville, un lieu...",
    radiusLabel: "Rayon",
    resultsNear: "resultats a proximite",
    noResults: "Aucune destination trouvee",
    explore: "Decouvrir",
    yourPosition: "Votre position",
    rating: "Note",
    distance: "Distance",
    duration: "Duree",
    catAll: "Tous",
    catBeach: "Plage",
    catCulture: "Culture",
    catCity: "Ville",
    catDesert: "Desert",
    catNature: "Nature",
    catHeritage: "Patrimoine",
    catMountain: "Montagne",
    catActivities: "Activites",

    // Planner Translations
    packTitle: "Planificateur de Voyage IA",
    packSubtitle: "Créez votre itinéraire de rêve au Maroc sur-mesure grâce à notre intelligence artificielle.",
    daysLabel: "Durée (jours)",
    daysPlaceholder: "De 1 à 14 jours",
    budgetLabel: "Style de budget",
    groupLabel: "Compagnons de voyage",
    apiKeyLabel: "Clé API Gemini (Optionnelle)",
    apiKeyPlaceholder: "Collez votre clé API Gemini ici...",
    generateBtn: "Générer mon Voyage",
    loadingTrip: "Conception de votre voyage en cours...",
    hotelHeading: "Sélections d'Hôtels & Resorts",
    riadHeading: "Sélections de Riads Traditionnels",
    itineraryHeading: "Itinéraire Quotidien Étape par Étape",
    viewOnMap: "Localisation (Google Maps)",
    ticketPrice: "Prix d'entrée :",
    ratingLabel: "Note :",
    soloTravel: "Solo",
    coupleTravel: "En couple",
    familyTravel: "En famille",
    friendsTravel: "Entre amis",
    cheapBudget: "Économique",
    moderateBudget: "Modéré",
    luxuryBudget: "Luxe",
    cheapDesc: "Voyager intelligemment avec un budget optimisé",
    moderateDesc: "Équilibre parfait entre confort et dépenses",
    luxuryDesc: "Expériences exclusives et hébergements haut de gamme",
    soloDesc: "Une aventure en solitaire à votre rythme",
    coupleDesc: "Escapade romantique à deux",
    familyDesc: "Souvenirs inoubliables pour toute la famille",
    friendsDesc: "Partage, fun et découvertes de groupe",
    noKeyAlert: "Aucune clé API configurée. Utilisation du planificateur de simulation premium.",

    // Apprendre Hub Translations
    learnHeroTitle: "Préparez votre voyage émotionnellement.",
    learnHeroCopy: "Entrez dans un parcours pensé pour votre voyage au Maroc. Un compagnon d'apprentissage qui s'adapte à votre itinéraire.",
    learnPathDarijaEyebrow: "Parcours recommandé",
    learnPathDarijaTitle: "Immersion Darija",
    learnPathDarijaDesc: "Travaillez les mots utiles, les scènes de voyage et les réponses naturelles pour échanger avec les Marocains.",
    learnPathDarijaCTA: "Entrer dans Darija",
    learnPathTifinaghEyebrow: "Exploration",
    learnPathTifinaghTitle: "Découvrir Tifinagh",
    learnPathTifinaghDesc: "Décodez les symboles Amazighs que vous croiserez lors de votre voyage.",
    learnPathTifinaghCTA: "Explorer Tifinagh",
    learnPathTipsEyebrow: "Préparation",
    learnPathTipsTitle: "Culture & Conseils",
    learnPathTipsDesc: "Savoir-vivre, étiquette du café, l'art de négocier et conseils pour un voyage authentique.",
    learnPathTipsCTA: "Voir les conseils",
    learnDestinationSelect: "Votre destination",
    learnUniversalPhrases: "Phrases universelles",
    learnPhrasesFor: "Phrases pour",
    learnContextAtmosphere: "Ambiance",

    // Destination Context Data Translations
    destMarrakech: "Marrakech",
    destFes: "Fès",
    destChefchaouen: "Chefchaouen",
    destEssaouira: "Essaouira",
    destAgadir: "Agadir",
    destCasablanca: "Casablanca",
    destTipSouk: "Négocier au Souk",
    destTipSoukDesc: "Attendez-vous à marchander fermement mais avec le sourire.",
    destTipRiad: "Étiquette des Riads",
    destTipRiadDesc: "On vous offrira souvent du thé à l'arrivée. Acceptez-le toujours !",
    destTipJemaa: "Jemaa el-Fna",
    destTipJemaaDesc: "Préparez de la petite monnaie pour les photos et spectacles.",
    tifSpotIrcam: "Panneaux de la Médina",
    tifSpotIrcamDesc: "De nombreuses rues de l'ancienne médina affichent désormais leur nom en Tifinagh.",
    tifSpotSigns: "Signalisation officielle",
    tifSpotSignsDesc: "Observez les panneaux gouvernementaux et administratifs.",
    destTipMedina: "S'orienter dans la Médina",
    destTipMedinaDesc: "Si vous êtes perdu, demandez à un commerçant plutôt qu'à quelqu'un dans la rue.",
    destTipTanneries: "Les Tanneries",
    destTipTanneriesDesc: "Acceptez la menthe qu'on vous donne à l'entrée pour masquer l'odeur forte.",
    destTipCeramics: "Céramiques",
    destTipCeramicsDesc: "Fès est célèbre pour sa poterie bleue. Excellent endroit pour acheter des souvenirs.",
    tifSpotUniv: "L'Université Al Quaraouiyine",
    tifSpotUnivDesc: "Des textes anciens de la plus vieille université intègrent parfois des éléments berbères.",
    destTipBlue: "La Ville Bleue",
    destTipBlueDesc: "La couleur bleue repousse traditionnellement les moustiques et garde les maisons fraîches.",
    destTipRif: "Les montagnes du Rif",
    destTipRifDesc: "Une région fière de son héritage montagnard et de ses traditions tisserandes.",
    destTipHashish: "Savoir dire non",
    destTipHashishDesc: "On vous proposera poliment, refusez simplement avec le sourire : 'La, chokran'.",
    tifSpotRif: "Artisanat Riffain",
    tifSpotRifDesc: "Cherchez les symboles berbères sur les poteries locales et les tissages.",
    destTipWind: "La ville des vents",
    destTipWindDesc: "Prévoyez toujours une veste, le vent (Chergui) peut être frais.",
    destTipGnawa: "Musique Gnawa",
    destTipGnawaDesc: "Essaouira est la capitale spirituelle de la musique Gnawa, aux rythmes hypnotiques.",
    destTipArgan: "L'huile d'Argan",
    destTipArganDesc: "C'est la région de l'arganier. Achetez dans les coopératives de femmes.",
    destTipSouss: "L'hospitalité Souss",
    destTipSoussDesc: "La région du Souss est connue pour son accueil exceptionnellement chaleureux.",
    destTipAmazigh: "Cœur de la culture Amazighe",
    destTipAmazighDesc: "Agadir est la plus grande ville majoritairement berbérophone du Maroc.",
    destTipSurf: "Culture Surf",
    destTipSurfDesc: "Taghazout à côté est le spot de surf par excellence. Ambiance très détendue.",
    tifSpotSouss: "L'Université d'Agadir",
    tifSpotSoussDesc: "L'une des premières à avoir promu la culture et la langue amazighes.",
    destTipHassan2: "Mosquée Hassan II",
    destTipHassan2Desc: "L'une des rares mosquées que les non-musulmans peuvent visiter (avec guide).",
    destTipModern: "Le Maroc Moderne",
    destTipModernDesc: "Ici, le code vestimentaire est beaucoup plus occidental et détendu.",
    destTipCorniche: "La Corniche",
    destTipCornicheDesc: "Le lieu parfait pour voir la jeunesse casablancaise le soir.",
    tifSpotInstitutions: "Institutions Majeures",
    tifSpotInstitutionsDesc: "Les grands bâtiments administratifs affichent presque tous le Tifinagh en façade.",

    // Travel Tips Data Translations
    tipCatAll: "Tout",
    tipCatEtiquette: "Savoir-vivre",
    tipCatCafe: "Culture Café",
    tipCatBargaining: "Négociation",
    tipCatTea: "Le Thé",
    tipCatTransport: "Transports",
    tipCatCustoms: "Coutumes",
    tipGreetingTitle: "Le Salam",
    tipGreetingContent: "Dire 'Salam alaykom' (Que la paix soit sur vous) avec la main droite sur le cœur est le salut ultime. Il ouvre toutes les portes.",
    tipRightHandTitle: "La Main Droite",
    tipRightHandContent: "Utilisez toujours votre main droite pour manger (surtout dans le plat commun), donner ou recevoir quelque chose. La main gauche est traditionnellement réservée à la toilette.",
    tipShoesTitle: "Les Chaussures",
    tipShoesContent: "Retirez toujours vos chaussures en entrant dans une maison marocaine ou un riad, sauf si votre hôte vous dit explicitement le contraire.",
    tipDressTitle: "Tenue Vestimentaire",
    tipDressContent: "Le Maroc est tolérant, mais s'habiller modestement (épaules et genoux couverts) montre du respect, particulièrement dans les médinas et zones rurales.",
    tipMosqueTitle: "Les Mosquées",
    tipMosqueContent: "À l'exception de la Mosquée Hassan II à Casablanca, l'entrée des mosquées est généralement interdite aux non-musulmans au Maroc.",
    tipCafeOrderTitle: "Au Café",
    tipCafeOrderContent: "S'asseoir en terrasse, souvent tourné vers la rue pour observer les passants, est le sport national. Commandez un 'Atay' (thé) ou un 'Nouss Nouss' (moitié café, moitié lait).",
    tipCafeSitTitle: "Prendre son temps",
    tipCafeSitContent: "Un café se boit lentement. Vous pouvez rester deux heures avec un seul café, c'est parfaitement normal et accepté.",
    tipCafeTipTitle: "Pourboire au café",
    tipCafeTipContent: "Il est de coutume de laisser 1 ou 2 dirhams de pourboire sur la table en partant, même pour un simple café.",
    tipBargainRuleTitle: "La Règle de Trois",
    tipBargainRuleContent: "Dans les souks (pas les magasins à prix fixe), divisez le prix initial par 3, et remontez doucement pour vous entendre à environ la moitié du prix de départ.",
    tipBargainSmileTitle: "Le Sourire",
    tipBargainSmileContent: "Marchander n'est pas un conflit, c'est un jeu social. Restez toujours souriant, poli et détendu. Ne vous fâchez jamais.",
    tipBargainWalkTitle: "Savoir Partir",
    tipBargainWalkContent: "L'outil de négociation le plus puissant : dire poliment non et s'éloigner lentement. Très souvent, le vendeur vous rappellera avec son meilleur prix.",
    tipFixedPriceTitle: "Où ne pas négocier",
    tipFixedPriceContent: "On ne négocie pas dans les restaurants, les supermarchés, les pharmacies, avec les taxis à compteur, ni dans les boutiques affichant 'Prix Fixe'.",
    tipTeaAcceptTitle: "Ne jamais refuser",
    tipTeaAcceptContent: "On vous offrira souvent du thé dans une boutique ou chez l'habitant. C'est un signe d'hospitalité. Le refuser peut être perçu comme impoli.",
    tipTeaPourTitle: "L'art de verser",
    tipTeaPourContent: "Le thé est versé de très haut pour le refroidir et l'oxygéner, créant une petite mousse appelée la 'couronne'. C'est une marque de respect.",
    tipTeaThreeTitle: "Les trois verres",
    tipTeaThreeContent: "Un proverbe dit : Le premier verre est doux comme la vie, le deuxième fort comme l'amour, le troisième amer comme la mort.",
    tipPetitTaxiTitle: "Les Petits Taxis",
    tipPetitTaxiContent: "Exigez toujours le compteur ('Khdem lcompteur'). S'il refuse, sortez et prenez-en un autre. Ne négociez pas un prix fixe à moins de bien connaître les tarifs.",
    tipGrandTaxiTitle: "Les Grands Taxis",
    tipGrandTaxiContent: "Ces taxis partagés font les trajets interurbains. Ils partent quand ils sont pleins (6 places). C'est très bon marché mais il faut être patient.",
    tipTippingTitle: "Les Pourboires",
    tipTippingContent: "Laissez 10% dans les bons restaurants, quelques dirhams aux bagagistes, et 1-2 Dhs aux gardiens de voiture gilet jaune (qui sont essentiels).",
    tipRamadanTitle: "Pendant le Ramadan",
    tipRamadanContent: "Ne mangez pas, ne buvez pas d'eau et ne fumez pas en public pendant la journée. De nombreux restaurants touristiques restent ouverts (souvent derrière des rideaux).",
    tipHammamTitle: "Le Hammam",
    tipHammamContent: "Un incontournable. Prenez votre savon noir, votre gant 'kessa' et préparez-vous à être vigoureusement frotté. Séparez les hommes et les femmes.",
    tipPhotoTitle: "Photographie",
    tipPhotoContent: "Demandez toujours la permission avant de photographier quelqu'un, particulièrement les femmes et les artisans. Certains vendeurs sur les places demanderont de l'argent.",
    tipHospitalityTitle: "L'Hospitalité",
    tipHospitalityContent: "L'accueil marocain n'est pas un mythe. Si vous êtes invité chez quelqu'un, apportez une petite pâtisserie ou du sucre, et préparez-vous à manger beaucoup !"
  },

  EN: {
    home: "Home",
    card: "Map",
    destination: "Destination",
    languages: "Learn",
    pack: "Planner",
    saved: "Saved",
    login: "Login",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    translation: "Translation",
    settings: "Settings",
    heroTitle: "Discover Beautiful Destinations",
    heroSubtitle: "Travel, Explore and Live unforgettable moments",
    exploreBtn: "Explore Now",
    topPlaces: "TOP PLACES",
    popularDestinations: "Popular Destinations",
    viewAll: "View All",
    chatbotGreeting: "Hello! I'm your AMUDUX assistant. How can I help you discover Morocco?",
    chatbotPlaceholder: "Write a message...",
    chatbotClear: "Clear",
    chatbotOnline: "Online",
    chatbotAssistant: "AMUDUX Assistant",
    chip1: "Marrakech",
    chip2: "Hotels",
    chip3: "Activities",
    chip4: "Prices",
    cardTitle: "Destinations Map",
    cardSubtitle: "Destinations near you",
    locating: "Locating...",
    locateMe: "My location",
    locError: "Geolocation denied. Showing Morocco.",
    searchPlaceholder: "Search a city, place...",
    radiusLabel: "Radius",
    resultsNear: "results nearby",
    noResults: "No destinations found",
    explore: "Explore",
    yourPosition: "Your position",
    rating: "Rating",
    distance: "Distance",
    duration: "Duration",
    catAll: "All",
    catBeach: "Beach",
    catCulture: "Culture",
    catCity: "City",
    catDesert: "Desert",
    catNature: "Nature",
    catHeritage: "Heritage",
    catMountain: "Mountain",
    catActivities: "Activities",

    // Planner Translations
    packTitle: "AI Trip Planner",
    packSubtitle: "Create your custom dream Morocco itinerary instantly with artificial intelligence.",
    daysLabel: "Duration (days)",
    daysPlaceholder: "From 1 to 14 days",
    budgetLabel: "Budget style",
    groupLabel: "Travel companions",
    apiKeyLabel: "Gemini API Key (Optional)",
    apiKeyPlaceholder: "Paste your Gemini API key here...",
    generateBtn: "Generate My Trip",
    loadingTrip: "Crafting your premium journey...",
    hotelHeading: "Selected Hotels & Resorts",
    riadHeading: "Traditional Riads Selection",
    itineraryHeading: "Day-by-Day Daily Plan",
    viewOnMap: "Location (Google Maps)",
    ticketPrice: "Ticket Price:",
    ratingLabel: "Rating:",
    soloTravel: "Solo",
    coupleTravel: "Couple",
    familyTravel: "Family",
    friendsTravel: "Friends",
    cheapBudget: "Cheap",
    moderateBudget: "Moderate",
    luxuryBudget: "Luxury",
    cheapDesc: "Travel smart with optimized budget plans",
    moderateDesc: "Perfect balance of comfort and spending",
    luxuryDesc: "Exclusive high-end stays and experiences",
    soloDesc: "A solo adventure set at your own pace",
    coupleDesc: "Romantic couple getaway",
    familyDesc: "Unforgettable memories for the whole family",
    friendsDesc: "Group fun, sharing, and adventures",
    noKeyAlert: "No API key configured. Utilizing premium simulation planner.",

    // Apprendre Hub Translations
    learnHeroTitle: "Prepare your journey emotionally.",
    learnHeroCopy: "Step into a learning path designed for your trip to Morocco. An educational companion adapting to your itinerary.",
    learnPathDarijaEyebrow: "Recommended path",
    learnPathDarijaTitle: "Darija Immersion",
    learnPathDarijaDesc: "Practice useful phrases, travel scenarios, and natural responses to interact with locals.",
    learnPathDarijaCTA: "Enter Darija",
    learnPathTifinaghEyebrow: "Exploration",
    learnPathTifinaghTitle: "Discover Tifinagh",
    learnPathTifinaghDesc: "Decode the Amazigh symbols you'll encounter during your trip.",
    learnPathTifinaghCTA: "Explore Tifinagh",
    learnPathTipsEyebrow: "Preparation",
    learnPathTipsTitle: "Culture & Tips",
    learnPathTipsDesc: "Etiquette, café culture, bargaining, and tips for an authentic journey.",
    learnPathTipsCTA: "View tips",
    learnDestinationSelect: "Your destination",
    learnUniversalPhrases: "Universal phrases",
    learnPhrasesFor: "Phrases for",
    learnContextAtmosphere: "Atmosphere",

    // Destination Context
    destMarrakech: "Marrakech",
    destFes: "Fes",
    destChefchaouen: "Chefchaouen",
    destEssaouira: "Essaouira",
    destAgadir: "Agadir",
    destCasablanca: "Casablanca",
    destTipSouk: "Bargaining at the Souk",
    destTipSoukDesc: "Expect to bargain firmly but always with a smile.",
    destTipRiad: "Riad Etiquette",
    destTipRiadDesc: "You will often be offered tea upon arrival. Always accept it!",
    destTipJemaa: "Jemaa el-Fna",
    destTipJemaaDesc: "Prepare small change for photos and performances.",
    tifSpotIrcam: "Medina Signs",
    tifSpotIrcamDesc: "Many streets in the ancient medina now display their name in Tifinagh.",
    tifSpotSigns: "Official Signage",
    tifSpotSignsDesc: "Observe government and administrative signs.",
    destTipMedina: "Navigating the Medina",
    destTipMedinaDesc: "If lost, ask a shopkeeper rather than someone in the street.",
    destTipTanneries: "The Tanneries",
    destTipTanneriesDesc: "Accept the mint given at the entrance to mask the strong smell.",
    destTipCeramics: "Ceramics",
    destTipCeramicsDesc: "Fes is famous for its blue pottery. Excellent place for souvenirs.",
    tifSpotUniv: "Al Quaraouiyine University",
    tifSpotUnivDesc: "Ancient texts from the oldest university sometimes include Berber elements.",
    destTipBlue: "The Blue City",
    destTipBlueDesc: "The blue color traditionally repels mosquitoes and keeps houses cool.",
    destTipRif: "Rif Mountains",
    destTipRifDesc: "A region proud of its mountain heritage and weaving traditions.",
    destTipHashish: "Knowing how to say no",
    destTipHashishDesc: "You might be offered politely, simply decline with a smile: 'La, chokran'.",
    tifSpotRif: "Riffian Crafts",
    tifSpotRifDesc: "Look for Berber symbols on local pottery and weavings.",
    destTipWind: "City of Winds",
    destTipWindDesc: "Always pack a jacket, the wind (Chergui) can be chilly.",
    destTipGnawa: "Gnawa Music",
    destTipGnawaDesc: "Essaouira is the spiritual capital of hypnotic Gnawa music.",
    destTipArgan: "Argan Oil",
    destTipArganDesc: "This is the Argan region. Buy from women's cooperatives.",
    destTipSouss: "Souss Hospitality",
    destTipSoussDesc: "The Souss region is known for its exceptionally warm welcome.",
    destTipAmazigh: "Heart of Amazigh culture",
    destTipAmazighDesc: "Agadir is the largest predominantly Berber-speaking city in Morocco.",
    destTipSurf: "Surf Culture",
    destTipSurfDesc: "Taghazout nearby is a prime surf spot. Very relaxed vibe.",
    tifSpotSouss: "Agadir University",
    tifSpotSoussDesc: "One of the first to promote Amazigh culture and language.",
    destTipHassan2: "Hassan II Mosque",
    destTipHassan2Desc: "One of the few mosques non-Muslims can visit (with a guide).",
    destTipModern: "Modern Morocco",
    destTipModernDesc: "Here, the dress code is much more westernized and relaxed.",
    destTipCorniche: "The Corniche",
    destTipCornicheDesc: "The perfect place to see Casablanca's youth in the evening.",
    tifSpotInstitutions: "Major Institutions",
    tifSpotInstitutionsDesc: "Large administrative buildings almost all display Tifinagh on their facades.",

    // Travel Tips
    tipCatAll: "All",
    tipCatEtiquette: "Etiquette",
    tipCatCafe: "Café Culture",
    tipCatBargaining: "Bargaining",
    tipCatTea: "Tea",
    tipCatTransport: "Transport",
    tipCatCustoms: "Customs",
    tipGreetingTitle: "The Salam",
    tipGreetingContent: "Saying 'Salam alaykom' (Peace be upon you) with your right hand over your heart is the ultimate greeting. It opens all doors.",
    tipRightHandTitle: "The Right Hand",
    tipRightHandContent: "Always use your right hand to eat (especially from a shared dish), give, or receive something. The left hand is traditionally reserved for hygiene.",
    tipShoesTitle: "Shoes",
    tipShoesContent: "Always remove your shoes when entering a Moroccan home or a riad, unless your host explicitly tells you otherwise.",
    tipDressTitle: "Dress Code",
    tipDressContent: "Morocco is tolerant, but dressing modestly (shoulders and knees covered) shows respect, particularly in medinas and rural areas.",
    tipMosqueTitle: "Mosques",
    tipMosqueContent: "With the exception of the Hassan II Mosque in Casablanca, entry to mosques is generally forbidden to non-Muslims in Morocco.",
    tipCafeOrderTitle: "At the Café",
    tipCafeOrderContent: "Sitting on a terrace, often facing the street to people-watch, is the national sport. Order an 'Atay' (tea) or a 'Nouss Nouss' (half coffee, half milk).",
    tipCafeSitTitle: "Taking your time",
    tipCafeSitContent: "Coffee is drunk slowly. You can stay for two hours with a single coffee, it's perfectly normal and accepted.",
    tipCafeTipTitle: "Tipping at the café",
    tipCafeTipContent: "It is customary to leave a 1 or 2 dirham tip on the table when leaving, even for just a coffee.",
    tipBargainRuleTitle: "The Rule of Three",
    tipBargainRuleContent: "In souks (not fixed-price shops), divide the initial price by 3, and slowly negotiate up to agree on about half the starting price.",
    tipBargainSmileTitle: "The Smile",
    tipBargainSmileContent: "Bargaining is not a conflict, it's a social game. Always remain smiling, polite, and relaxed. Never get angry.",
    tipBargainWalkTitle: "Knowing when to walk away",
    tipBargainWalkContent: "The most powerful negotiation tool: politely saying no and slowly walking away. Very often, the seller will call you back with their best price.",
    tipFixedPriceTitle: "Where NOT to bargain",
    tipFixedPriceContent: "Do not bargain in restaurants, supermarkets, pharmacies, with metered taxis, or in shops displaying 'Prix Fixe'.",
    tipTeaAcceptTitle: "Never refuse",
    tipTeaAcceptContent: "You will often be offered tea in a shop or someone's home. It's a sign of hospitality. Refusing it can be perceived as impolite.",
    tipTeaPourTitle: "The art of pouring",
    tipTeaPourContent: "Tea is poured from high up to cool and oxygenate it, creating a little foam called the 'crown'. It's a mark of respect.",
    tipTeaThreeTitle: "The three glasses",
    tipTeaThreeContent: "A proverb says: The first glass is gentle as life, the second strong as love, the third bitter as death.",
    tipPetitTaxiTitle: "Petit Taxis",
    tipPetitTaxiContent: "Always insist on the meter ('Khdem lcompteur'). If they refuse, exit and take another. Don't negotiate a fixed price unless you know the rates well.",
    tipGrandTaxiTitle: "Grand Taxis",
    tipGrandTaxiContent: "These shared taxis do intercity routes. They leave when full (6 seats). It's very cheap but requires patience.",
    tipTippingTitle: "Tipping",
    tipTippingContent: "Leave 10% in good restaurants, a few dirhams for porters, and 1-2 Dhs for the yellow-vested car guards (who are essential).",
    tipRamadanTitle: "During Ramadan",
    tipRamadanContent: "Do not eat, drink water, or smoke in public during the day. Many tourist restaurants remain open (often behind curtains).",
    tipHammamTitle: "The Hammam",
    tipHammamContent: "A must-do. Take your black soap, your 'kessa' glove, and prepare to be vigorously scrubbed. Men and women are separated.",
    tipPhotoTitle: "Photography",
    tipPhotoContent: "Always ask permission before photographing someone, particularly women and artisans. Some performers in squares will ask for money.",
    tipHospitalityTitle: "Hospitality",
    tipHospitalityContent: "Moroccan hospitality is not a myth. If you are invited to someone's home, bring a small pastry or sugar, and prepare to eat a lot!"
  },

  AR: {
    home: "\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629",
    card: "\u0627\u0644\u062e\u0631\u064a\u0637\u0629",
    destination: "\u0627\u0644\u0648\u062c\u0647\u0627\u062a",
    languages: "تعلّم",
    pack: "مخطط الرحلات",
    saved: "\u0627\u0644\u0645\u062d\u0641\u0648\u0638\u0627\u062a",
    login: "\u062a\u0633\u062c\u064a\u0644 \u0627\u0644\u062f\u062e\u0648\u0644",
    darkMode: "\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0627\u0643\u0646",
    lightMode: "\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0641\u0627\u062a\u062d",
    translation: "\u0627\u0644\u062a\u0631\u062c\u0645\u0629",
    settings: "\u0627\u0644\u0625\u0639\u062f\u0627\u062f\u0627\u062a",
    heroTitle: "\u0627\u0643\u062a\u0634\u0641 \u0648\u062c\u0647\u0627\u062a \u0631\u0627\u0626\u0639\u0629",
    heroSubtitle: "\u0633\u0627\u0641\u0631\u060c \u0627\u0633\u062a\u0643\u0634\u0641 \u0648\u0639\u0634 \u0644\u062d\u0638\u0627\u062a \u0644\u0627 \u062a\u064f\u0646\u0633\u0649",
    exploreBtn: "\u0627\u0633\u062a\u0643\u0634\u0641 \u0627\u0644\u0622\u0646",
    topPlaces: "\u0623\u0641\u0636\u0644 \u0627\u0644\u0623\u0645\u0627\u0643\u0646",
    popularDestinations: "\u0627\u0644\u0648\u062c\u0647\u0627\u062a \u0627\u0644\u0634\u0639\u0628\u064a\u0629",
    viewAll: "\u0639\u0631\u0636 \u0627\u0644\u0643\u0644",
    chatbotGreeting: "\u0645\u0631\u062d\u0628\u0627! \u0623\u0646\u0627 \u0645\u0633\u0627\u0639\u062f\u0643 \u0641\u064a AMUDUX.",
    chatbotPlaceholder: "\u0627\u0643\u062a\u0628 \u0631\u0633\u0627\u0644\u0629...",
    chatbotClear: "\u0645\u0633\u062d",
    chatbotOnline: "\u0645\u062a\u0635\u0644",
    chatbotAssistant: "\u0645\u0633\u0627\u0639\u062f AMUDUX",
    chip1: "\u0645\u0631\u0627\u0643\u0634",
    chip2: "\u0627\u0644\u0641\u0646\u0627\u062f\u0642",
    chip3: "\u0627\u0644\u0623\u0646\u0634\u0637\u0629",
    chip4: "\u0627\u0644\u0623\u0633\u0639\u0627\u0631",
    cardTitle: "\u062e\u0631\u064a\u0637\u0629 \u0627\u0644\u0648\u062c\u0647\u0627\u062a",
    cardSubtitle: "\u0627\u0644\u0648\u062c\u0647\u0627\u062a \u0627\u0644\u0642\u0631\u064a\u0628\u0629 \u0645\u0646\u0643",
    locating: "\u062c\u0627\u0631\u064a\u064b \u062a\u062d\u062f\u064a\u062f \u0627\u0644\u0645\u0648\u0642\u0639...",
    locateMe: "\u0645\u0648\u0642\u0639\u064a",
    locError: "\u062a\u0645 \u0631\u0641\u0636 \u0627\u0644\u0645\u0648\u0642\u0639. \u0639\u0631\u0636 \u0627\u0644\u0645\u063a\u0631\u0628.",
    searchPlaceholder: "\u0627\u0628\u062d\u062b \u0639\u0646 \u0645\u062f\u064a\u0646\u0629 \u0623\u0648 \u0645\u0643\u0627\u0646...",
    radiusLabel: "\u0627\u0644\u0646\u0637\u0627\u0642",
    resultsNear: "\u0646\u062a\u064a\u062c\u0629 \u0642\u0631\u064a\u0628\u0629",
    noResults: "\u0644\u0627 \u062a\u0648\u062c\u062f \u0648\u062c\u0647\u0627\u062a",
    explore: "\u0627\u0633\u062a\u0643\u0634\u0641",
    yourPosition: "\u0645\u0648\u0642\u0639\u0643",
    rating: "\u0627\u0644\u062a\u0642\u064a\u064a\u0645",
    distance: "\u0627\u0644\u0645\u0633\u0627\u0641\u0629",
    duration: "\u0627\u0644\u0645\u062f\u0629",
    catAll: "\u0627\u0644\u0643\u0644",
    catBeach: "\u0634\u0627\u0637\u0626",
    catCulture: "\u062b\u0642\u0627\u0641\u0629",
    catCity: "\u0645\u062f\u064a\u0646\u0629",
    catDesert: "\u0635\u062d\u0631\u0627\u0621",
    catNature: "\u0637\u0628\u064a\u0639\u0629",
    catHeritage: "\u062a\u0631\u0627\u062b",
    catMountain: "\u062c\u0628\u0627\u0644",
    catActivities: "\u0623\u0646\u0634\u0637\u0629",

    // Planner Translations
    packTitle: "\u0645\u062e\u0637\u0637 \u0627\u0644\u0631\u062d\u0644\u0627\u062a \u0628\u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a",
    packSubtitle: "\u0623\u0646\u0634\u0626 \u062e\u0637\u0629 \u0633\u0641\u0631 \u0645\u062e\u0635\u0635\u0629 \u0644\u0644\u0645\u063a\u0631\u0628 \u0641\u064a \u062b\u0648\u0627\u0646\u064d \u0645\u0639\u062f\u0648\u062f\u0629 \u0628\u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a.",
    daysLabel: "\u0627\u0644\u0645\u062f\u0629 (\u0628\u0627\u0644\u0623\u064a\u0627\u0645)",
    daysPlaceholder: "\u0645\u0646 1 \u0625\u0644\u0649 14 \u064a\u0648\u0645\u0627\u064b",
    budgetLabel: "\u0623\u0633\u0644\u0648\u0628 \u0627\u0644\u0645\u064a\u0632\u0627\u0646\u064a\u0629",
    groupLabel: "\u0631\u0641\u0642\u0627\u0621 \u0627\u0644\u0633\u0641\u0631",
    apiKeyLabel: "\u0645\u0641\u062a\u0627\u062d API \u0644\u0640 Gemini (\u0627\u062e\u062a\u064a\u0627\u0631\u064a)",
    apiKeyPlaceholder: "\u0623\u0644\u0635\u0642 \u0645\u0641\u062a\u0627\u062d Gemini \u0627\u0644\u062e\u0627\u0635 \u0628\u0643 \u0647\u0646\u0627...",
    generateBtn: "\u0623\u0646\u0634\u0626 \u0631\u062d\u0644\u062a\u064a",
    loadingTrip: "\u062c\u0627\u0631\u064a \u062a\u0635\u0645\u064a\u0645 \u0631\u062d\u0644\u062a\u0643 \u0627\u0644\u0641\u0627\u062e\u0631\u0629...",
    hotelHeading: "\u0627\u0644\u0641\u0646\u0627\u062f\u0642 \u0648\u0627\u0644\u0645\u0646\u062a\u062c\u0639\u0627\u062a \u0627\u0644\u0645\u0642\u062a\u0631\u062d\u0629",
    riadHeading: "\u0627\u0644\u0631\u064a\u0627\u0636\u0627\u062a \u0627\u0644\u062a\u0642\u0644\u064a\u062f\u064a\u0629 \u0627\u0644\u0645\u0642\u062a\u0631\u062d\u0629",
    itineraryHeading: "\u0645\u062e\u0637\u0637 \u0627\u0644\u0631\u062d\u0644\u0629 \u064a\u0648\u0645\u0627\u064b \u0628\u064a\u0648\u0645",
    viewOnMap: "\u0627\u0644\u0645\u0648\u0642\u0639 \u0639\u0644\u0649 \u062e\u0631\u0627\u0626\u0637 Google",
    ticketPrice: "\u0633\u0639\u0631 \u0627\u0644\u062a\u0630\u0643\u0631\u0629:",
    ratingLabel: "\u0627\u0644\u062a\u0642\u064a\u064a\u0645:",
    soloTravel: "\u0641\u0631\u062f\u064a",
    coupleTravel: "\u0632\u0648\u062c\u0627\u0646",
    familyTravel: "\u0639\u0627\u0626\u0644\u064a",
    friendsTravel: "\u0623\u0635\u062f\u0642\u0627\u0621",
    cheapBudget: "\u0627\u0642\u062a\u0635\u0627\u062f\u064a",
    moderateBudget: "\u0645\u062a\u0648\u0633\u0637",
    luxuryBudget: "\u0641\u0627\u062e\u0631",
    cheapDesc: "\u0633\u0627\u0641\u0631 \u0628\u0630\u0643\u0627\u0621 \u0645\u0639 \u0645\u064a\u0632\u0627\u0646\u064a\u0629 \u0645\u062d\u0633\u0646\u0629 \u0648\u0627\u0642\u062a\u0635\u0627\u062f\u064a\u0629",
    moderateDesc: "\u062a\u0648\u0627\u0632\u0646 \u0645\u062b\u0627\u0644\u064a \u0628\u064a\u0646 \u0627\u0644\u0631\u0627\u062d\u0629 \u0648\u0627\u0644\u0625\u0646\u0641\u0627\u0642",
    luxuryDesc: "\u0625\u0642\u0627\u0645\u0627\u062a \u0631\u0627\u0642\u064a\u0629 \u0648\u062a\u062c\u0627\u0631\u0628 \u062d\u0635\u0631\u064a\u0629 \u0641\u0627\u062e\u0631\u0629",
    soloDesc: "\u0645\u063a\u0627\u0645\u0631\u0629 \u0641\u0631\u062f\u064a\u0629 \u0645\u0645\u062a\u0639\u0629 \u0628\u062c\u062f\u0648\u0644\u0643 \u0627\u0644\u062e\u0627\u0635",
    coupleDesc: "\u0639\u0637\u0644\u0629 \u0631\u0648\u0645\u0627\u0646\u0633\u064a\u0629 \u0631\u0627\u0626\u0639\u0629 \u0644\u0634\u062e\u0635\u064a\u0646",
    familyDesc: "\u0630\u0643\u0631\u064a\u0627\u062a \u0644\u0627 \u062a\u064f\u0646\u0633\u0649 \u0644\u062c\u0645\u064a\u0639 \u0623\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629",
    friendsDesc: "\u0645\u0634\u0627\u0631\u0643\u0629 \u0648\u0645\u062a\u0639\u0629 \u0648\u0645\u063a\u0627\u0645\u0631\u0629 \u062c\u0645\u0627\u0639\u064a\u0629",
    noKeyAlert: "\u0644\u0645 \u064a\u062a\u0645 \u062a\u0643\u0648\u064a\u0646 \u0645\u0641\u062a\u0627\u062d API. \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0645\u062e\u0637\u0637 \u0627\u0644\u0645\u062d\u0627\u0643\u0627\u0629 \u0627\u0644\u0641\u0627\u062e\u0631.",

    // Apprendre Hub Translations
    learnHeroTitle: "استعد لرحلتك عاطفياً.",
    learnHeroCopy: "ادخل في مسار تعليمي مصمم لرحلتك إلى المغرب. رفيق تعليمي يتكيف مع مسار رحلتك.",
    learnPathDarijaEyebrow: "المسار الموصى به",
    learnPathDarijaTitle: "الدارجة",
    learnPathDarijaDesc: "مارس العبارات المفيدة وسيناريوهات السفر والردود الطبيعية للتواصل مع السكان المحليين.",
    learnPathDarijaCTA: "تعلّم الدارجة",
    learnPathTifinaghEyebrow: "استكشاف",
    learnPathTifinaghTitle: "اكتشف تيفيناغ",
    learnPathTifinaghDesc: "فك رموز الأمازيغية التي ستواجهها خلال رحلتك.",
    learnPathTifinaghCTA: "استكشف تيفيناغ",
    learnPathTipsEyebrow: "تحضير",
    learnPathTipsTitle: "الثقافة والنصائح",
    learnPathTipsDesc: "آداب السلوك، ثقافة المقاهي، المساومة، ونصائح لرحلة أصيلة.",
    learnPathTipsCTA: "عرض النصائح",
    learnDestinationSelect: "وجهتك",
    learnUniversalPhrases: "عبارات عالمية",
    learnPhrasesFor: "عبارات لـ",
    learnContextAtmosphere: "الأجواء",

    // Destination Context
    destMarrakech: "مراكش",
    destFes: "فاس",
    destChefchaouen: "شفشاون",
    destEssaouira: "الصويرة",
    destAgadir: "أكادير",
    destCasablanca: "الدار البيضاء",
    destTipSouk: "المساومة في السوق",
    destTipSoukDesc: "توقع أن تساوم بحزم ولكن بابتسامة دائمًا.",
    destTipRiad: "آداب الرياض",
    destTipRiadDesc: "غالبًا ما سيُعرض عليك الشاي عند الوصول. اقبله دائمًا!",
    destTipJemaa: "جامع الفنا",
    destTipJemaaDesc: "جهز الفكة من أجل التقاط الصور والعروض.",
    tifSpotIrcam: "لافتات المدينة القديمة",
    tifSpotIrcamDesc: "العديد من الشوارع في المدينة القديمة تعرض الآن أسماءها بحرف التيفيناغ.",
    tifSpotSigns: "اللافتات الرسمية",
    tifSpotSignsDesc: "راقب اللافتات الحكومية والإدارية.",
    destTipMedina: "التجول في المدينة القديمة",
    destTipMedinaDesc: "إذا ضللت طريقك، فاسأل صاحب متجر بدلاً من شخص في الشارع.",
    destTipTanneries: "المدابغ",
    destTipTanneriesDesc: "اقبل النعناع الذي يُعطى لك عند المدخل لإخفاء الرائحة القوية.",
    destTipCeramics: "الخزف",
    destTipCeramicsDesc: "تشتهر فاس بالفخار الأزرق. مكان ممتاز لشراء الهدايا التذكارية.",
    tifSpotUniv: "جامعة القرويين",
    tifSpotUnivDesc: "النصوص القديمة من أقدم جامعة تتضمن أحيانًا عناصر أمازيغية.",
    destTipBlue: "المدينة الزرقاء",
    destTipBlueDesc: "اللون الأزرق يطرد البعوض تقليديًا ويحافظ على برودة المنازل.",
    destTipRif: "جبال الريف",
    destTipRifDesc: "منطقة فخورة بتراثها الجبلي وتقاليد النسيج.",
    destTipHashish: "كيف تقول لا",
    destTipHashishDesc: "قد يُعرض عليك الأمر بأدب، ما عليك سوى الرفض بابتسامة: 'لا، شكراً'.",
    tifSpotRif: "الحرف اليدوية في الريف",
    tifSpotRifDesc: "ابحث عن الرموز الأمازيغية على الفخار المحلي والمنسوجات.",
    destTipWind: "مدينة الرياح",
    destTipWindDesc: "احزم دائمًا سترة، فالرياح (الشرقي) يمكن أن تكون باردة.",
    destTipGnawa: "موسيقى كناوة",
    destTipGnawaDesc: "الصويرة هي العاصمة الروحية لموسيقى كناوة المنومة.",
    destTipArgan: "زيت الأركان",
    destTipArganDesc: "هذه هي منطقة الأركان. اشترِ من تعاونيات النساء.",
    destTipSouss: "ضيافة سوس",
    destTipSoussDesc: "تُعرف منطقة سوس بترحيبها الحار بشكل استثنائي.",
    destTipAmazigh: "قلب الثقافة الأمازيغية",
    destTipAmazighDesc: "أكادير هي أكبر مدينة ناطقة بالأمازيغية في المغرب.",
    destTipSurf: "ثقافة ركوب الأمواج",
    destTipSurfDesc: "تغازوت القريبة هي موقع رئيسي لركوب الأمواج. أجواء مريحة للغاية.",
    tifSpotSouss: "جامعة أكادير",
    tifSpotSoussDesc: "واحدة من أوائل الجامعات التي روجت للثقافة واللغة الأمازيغية.",
    destTipHassan2: "مسجد الحسن الثاني",
    destTipHassan2Desc: "من المساجد القليلة التي يمكن لغير المسلمين زيارتها (مع مرشد).",
    destTipModern: "المغرب الحديث",
    destTipModernDesc: "هنا، قواعد اللباس غربية ومريحة أكثر بكثير.",
    destTipCorniche: "الكورنيش",
    destTipCornicheDesc: "المكان المثالي لرؤية شباب الدار البيضاء في المساء.",
    tifSpotInstitutions: "المؤسسات الكبرى",
    tifSpotInstitutionsDesc: "تعرض جميع المباني الإدارية الكبيرة تقريبًا تيفيناغ على واجهاتها.",

    // Travel Tips
    tipCatAll: "الكل",
    tipCatEtiquette: "آداب السلوك",
    tipCatCafe: "ثقافة المقاهي",
    tipCatBargaining: "المساومة",
    tipCatTea: "الشاي",
    tipCatTransport: "النقل",
    tipCatCustoms: "العادات",
    tipGreetingTitle: "السلام",
    tipGreetingContent: "قول 'السلام عليكم' مع وضع يدك اليمنى على قلبك هو التحية المطلقة. يفتح كل الأبواب.",
    tipRightHandTitle: "اليد اليمنى",
    tipRightHandContent: "استخدم دائمًا يدك اليمنى لتناول الطعام (خاصة من الطبق المشترك) أو الإعطاء أو التلقي. اليد اليسرى مخصصة تقليديًا للنظافة.",
    tipShoesTitle: "الأحذية",
    tipShoesContent: "اخلع حذاءك دائمًا عند دخول منزل مغربي أو رياض، ما لم يخبرك مضيفك بخلاف ذلك.",
    tipDressTitle: "اللباس",
    tipDressContent: "المغرب متسامح، لكن اللباس المحتشم (تغطية الكتفين والركبتين) يظهر الاحترام، خاصة في المدن القديمة والمناطق الريفية.",
    tipMosqueTitle: "المساجد",
    tipMosqueContent: "باستثناء مسجد الحسن الثاني في الدار البيضاء، يُمنع عمومًا على غير المسلمين دخول المساجد في المغرب.",
    tipCafeOrderTitle: "في المقهى",
    tipCafeOrderContent: "الجلوس على الشرفة، وغالبًا ما يكون مواجهًا للشارع لمراقبة الناس، هو رياضة وطنية. اطلب 'أتاي' (شاي) أو 'نص نص' (نصف قهوة، نصف حليب).",
    tipCafeSitTitle: "خذ وقتك",
    tipCafeSitContent: "تُشرب القهوة ببطء. يمكنك البقاء لمدة ساعتين بقهوة واحدة، وهو أمر طبيعي ومقبول تمامًا.",
    tipCafeTipTitle: "إكرامية المقهى",
    tipCafeTipContent: "من المعتاد ترك إكرامية بقيمة درهم أو درهمين على الطاولة عند المغادرة، حتى لو كان ذلك من أجل قهوة فقط.",
    tipBargainRuleTitle: "قاعدة الثلاثة",
    tipBargainRuleContent: "في الأسواق (وليس المحلات ذات الأسعار الثابتة)، اقسم السعر المبدئي على 3، وتفاوض ببطء للاتفاق على نصف السعر المبدئي تقريبًا.",
    tipBargainSmileTitle: "الابتسامة",
    tipBargainSmileContent: "المساومة ليست صراعًا، إنها لعبة اجتماعية. ابق دائمًا مبتسمًا ومهذبًا ومسترخيًا. لا تغضب أبدًا.",
    tipBargainWalkTitle: "متى تغادر",
    tipBargainWalkContent: "أقوى أداة للتفاوض: الرفض بأدب والابتعاد ببطء. في كثير من الأحيان، سيعاود البائع الاتصال بك بأفضل سعر لديه.",
    tipFixedPriceTitle: "أين لا تساوم",
    tipFixedPriceContent: "لا تساوم في المطاعم أو السوبر ماركت أو الصيدليات أو سيارات الأجرة ذات العدادات أو في المتاجر التي تعرض 'سعر ثابت'.",
    tipTeaAcceptTitle: "لا ترفض أبداً",
    tipTeaAcceptContent: "غالبًا ما سيُعرض عليك الشاي في متجر أو في منزل شخص ما. إنها علامة على كرم الضيافة. رفضها يمكن أن يُنظر إليه على أنه غير مهذب.",
    tipTeaPourTitle: "فن الصب",
    tipTeaPourContent: "يُسكب الشاي من مكان مرتفع لتبريده وإمداده بالأكسجين، مما يخلق رغوة صغيرة تسمى 'التاج'. إنها علامة على الاحترام.",
    tipTeaThreeTitle: "الكؤوس الثلاثة",
    tipTeaThreeContent: "يقول مثل: الكأس الأول لطيف كالحياة، والثاني قوي كالحب، والثالث مر كالموت.",
    tipPetitTaxiTitle: "سيارات الأجرة الصغيرة",
    tipPetitTaxiContent: "أصر دائمًا على تشغيل العداد ('خدم العداد'). إذا رفضوا، اخرج واستقل سيارة أخرى. لا تتفاوض على سعر ثابت ما لم تكن تعرف الأسعار جيدًا.",
    tipGrandTaxiTitle: "سيارات الأجرة الكبيرة",
    tipGrandTaxiContent: "تقوم سيارات الأجرة المشتركة هذه بمسارات بين المدن. تغادر عندما تمتلئ (6 مقاعد). إنها رخيصة جدًا ولكنها تتطلب الصبر.",
    tipTippingTitle: "الإكراميات",
    tipTippingContent: "اترك 10٪ في المطاعم الجيدة، وبضعة دراهم للحمالين، و 1-2 درهم لحراس السيارات ذوي السترات الصفراء (الذين هم ضروريون).",
    tipRamadanTitle: "خلال شهر رمضان",
    tipRamadanContent: "لا تأكل أو تشرب الماء أو تدخن في الأماكن العامة خلال النهار. تظل العديد من المطاعم السياحية مفتوحة (غالبًا خلف الستائر).",
    tipHammamTitle: "الحمام",
    tipHammamContent: "لا بد من القيام به. خذ الصابون الأسود وقفاز 'الكيسة' واستعد للفرك بقوة. يفصل بين الرجال والنساء.",
    tipPhotoTitle: "التصوير",
    tipPhotoContent: "اطلب الإذن دائمًا قبل تصوير شخص ما، خاصة النساء والحرفيين. سيطلب بعض الفنانين في الساحات المال.",
    tipHospitalityTitle: "الضيافة",
    tipHospitalityContent: "الضيافة المغربية ليست أسطورة. إذا تمت دعوتك إلى منزل شخص ما، فأحضر معك معجنات صغيرة أو سكرًا، واستعد لتناول الكثير من الطعام!"
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const savedLang = localStorage.getItem("app-language");
    return savedLang || "FR";
  });

  const t = (key) => translations[lang][key] || key;
  const isRTL = lang === "AR";

  useEffect(() => {
    localStorage.setItem("app-language", lang);
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      <div dir={isRTL ? "rtl" : "ltr"}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;